name: Artifact

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches: [master, main]

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '15.14.0'
      - name: Get Info
        run: |
          echo "::set-output name=id::$(jq -r '.id' plugin.json)"
          echo "::set-output name=version::$(jq -r '.version' plugin.json)"
        id: info
      - name: Build Artifact
        run: |
          cd ${{ github.workspace }}/webapp
          npm install --legacy-peer-deps
          cd .. && make dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.info.outputs.id }}-${{ steps.info.outputs.version }}
          path: dist/${{ steps.info.outputs.id }}-${{ steps.info.outputs.version }}.tar.gz
